[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {workspace = true}

[dev-dependencies]
server = {workspace = true}
ctor = "0.2.8"
lazy_static = "1.4.0"
