[package]
name = "chest"
version = "0.1.0"
edition = "2021"

[dependencies]
fasthash = "0.4.0"
rmp-serde = "1.2.0"
serde = { version = "1.0.198", features = ["derive"] }
errors = {workspace = true}
itertools = "0.12.1"

[dev-dependencies]
cuid = "1.3.2"
