[package]
name = "server-value"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chest = {workspace = true}
serde = { version = "1.0.198", features = ["derive"] }
rmp-serde = "1.2.0"
