[package]
name = "runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
errors = {workspace = true}
chest = {workspace = true}
query = {workspace = true}
grimoire = {workspace = true}

[dev-dependencies]
cuid = "1.3.2"
